name: Phoenix API CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'phoenix-api/**'
  pull_request:
    paths:
      - 'phoenix-api/**'

jobs:
  test-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./phoenix-api
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install poetry && poetry install
      - name: Run tests
        run: poetry run pytest
      - name: Run linting
        run: poetry run ruff check . && poetry run black --check .

  deploy-railway:
    needs: test-lint
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: railway/cli-action@v1
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          # IMPORTANT: Set the Railway Service ID in your project settings
          # Example: railway_service: "phoenix-api"
